
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_url: http://config-service-svc
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  hostname: "mysql-0.mysql"


